name       : gerbv
version    : 2.9.2
release    : 6
source     :
    - https://github.com/gerbv/gerbv/archive/refs/tags/v2.9.2.tar.gz : bea49fc5aa861caf1c0050be008f9316f502d318cb33588ffe59eece4ddbfcea
homepage   : https://gerbv.github.io/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Free/Open Source Gerber Viewer
description: |
    This is a maintained fork of gerbv, carrying mostly bugfixes. Gerbv is a viewer for Gerber RS-274X files, Excellon drill files, and CSV pick-and-place files.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-2.0)
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    sed -i "21 i VERSION=%version%" src/Makefile.am
    sed -i "64 i #define VERSION \"%version%\"" src/gerbv.h

    %autogen --disable-static --disable-update-desktop-database
build      : |
    %make
install    : |
    %make_install
