name       : gerbv
version    : 2.7.0
release    : 2
source     :
    - https://sourceforge.net/projects/gerbv/files/gerbv/gerbv-2.7.0/gerbv-2.7.0.tar.gz/download : c5ee808c4230ce6be3ad10ab63c547098386d43022704de25ddb9378e62053b4
homepage   : http://gerbv.geda-project.org/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Free/Open Source Gerber Viewer
description: |
    Gerbv is a viewer for Gerber RS-274X files, Excellon drill files, and CSV pick-and-place files.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure --disable-static --disable-update-desktop-database
build      : |
    %make
install    : |
    %make_install
